version: "3"
services: 
  api-server: 
    image: api-server
    ports:
      - "1234:1234"
    networks:
      - todolist-app
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - todolist-app
    volumes:
      - mongo-data:/data/db
  networks:
    todolist-app:
      driver: bridge
  volumes:
    mongo-data:
      driver: local